# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-cheri-toolchain"
BBFILE_PATTERN_meta-cheri-toolchain = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-cheri-toolchain = "8"

LAYERDEPENDS_meta-cheri-toolchain = " core clang-layer"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_meta-cheri-toolchain = "1"

LAYERSERIES_COMPAT_meta-cheri-toolchain = "scarthgap"

# Support for Cheri
INHERIT:prepend = "cheri "

# This needs to be set here, before we include tclibc-glibc.inc
TCLIBC = "musl"

META_CHERI_FILES_DIR = "${LAYERDIR}/files"

META_CHERI_LLVM_PROJECT_REPO ?= "github.com/CHERI-Alliance/llvm-project.git"
META_CHERI_LLVM_PROJECT_BRANCH ?= "codasip-cheri-riscv-19"
META_CHERI_LLVM_PROJECT_PROTOCOL ?= "https"

META_CHERI_MUSL_REPO ?= "github.com/CHERI-Alliance/musl.git"
META_CHERI_MUSL_BRANCH ?= "codasip-cheri-riscv"
META_CHERI_MUSL_PROTOCOL ?= "https"

# Override the meta-clang's nonclangable
require conf/nonclangable-cheri.conf

LLVMVERSION = "19.0.0"
