# Override variables set in meta-clang's nonclangable.conf
# NOTE this requires this file to be included after meta-clang's, and this is based on the
# order of layers in bblayers.conf.

LDFLAGS:remove:pn-zlib:toolchain-clang = "-fuse-ld=bfd"

# meta-clang sets this to gcc, but this appears to be because of a problem with mozjs,
# which we aren't using
TOOLCHAIN:pn-polkit = "clang"

# elfutils now builds with libc++, so the forcing libstdc++ is no longer required
LIBCPLUSPLUS:pn-elfutils:toolchain-clang = "-stdlib=libc++"

# It no longer appears necessary for force rync to be built with gcc
TOOLCHAIN:pn-rsync = "clang"

# Override the toolchain specified in nonclangable.
TOOLCHAIN:pn-libssp-nonshared = "clang"
