# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-codasip-cheri"
BBFILE_PATTERN_meta-codasip-cheri = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-codasip-cheri = "15"

BBFILES_DYNAMIC += " \
    openembedded-layer:${LAYERDIR}/dynamic-layers/openembedded-layer/*/*/*.bb \
    openembedded-layer:${LAYERDIR}/dynamic-layers/openembedded-layer/*/*/*.bbappend \
"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_meta-codasip-cheri = "1"

LAYERSERIES_COMPAT_meta-codasip-cheri = "nanbield"

# Support for Cheri
DISTROOVERRIDES:append = "${@bb.utils.contains('DISTRO_FEATURES', 'cheri', ':cheri', '', d)}"
DISTRO_FEATURES_FILTER_NATIVE:append = " cheri"
INHERIT:prepend = "codasip-cheri "

# This needs to be set here, before we include tclibc-glibc.inc
TCLIBC = "musl"

CODASIP_GIT_BRANCH = "hobgoblin-cheri"

# We can't currently build the cheri enabled qemu for non-cheri system
# so substitue the dummy (1.0) version.
# (QEMUVERSION is used by poky for the PREFERRED_VERSION of qemu, qemu-native
# and nativesdk-qemu, not qemu-system-native.)
QEMUVERSION = "1.0"

QEMU_TARGETS:cheri = "riscv64 riscv64cheri x86_64"
PREFERRED_VERSION_qemu-system-native ?= "8.2%"
PREFERRED_VERSION_qemu-system-native:cheri ?= "6.2%"
