# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-cheri"
BBFILE_PATTERN_meta-cheri = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-cheri = "15"

BBFILES_DYNAMIC += " \
    openembedded-layer:${LAYERDIR}/dynamic-layers/openembedded-layer/*/*/*.bb \
    openembedded-layer:${LAYERDIR}/dynamic-layers/openembedded-layer/*/*/*.bbappend \
    gnome-layer:${LAYERDIR}/dynamic-layers/gnome-layer/*/*/*.bbappend \
    networking-layer:${LAYERDIR}/dynamic-layers/networking-layer/*/*/*.bbappend \
    multimedia-layer:${LAYERDIR}/dynamic-layers/multimedia-layer/*/*/*.bbappend \
"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_meta-cheri = "1"

LAYERSERIES_COMPAT_meta-cheri = "scarthgap"

# Support for Cheri
INHERIT:prepend = "cheri "

# This needs to be set here, before we include tclibc-glibc.inc
TCLIBC = "musl"

META_CHERI_FILES_DIR = "${LAYERDIR}/files"

CODASIP_GIT_BRANCH = "hobgoblin-cheri"
