# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-cheri-codasip-bsp"
BBFILE_PATTERN_meta-cheri-codasip-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-cheri-codasip-bsp = "9"

LAYERDEPENDS_meta-cheri-codasip-bsp = " meta-cheri-toolchain"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_meta-cheri-codasip-bsp = "1"

LAYERSERIES_COMPAT_meta-cheri-codasip-bsp = "scarthgap"

META_CHERI_LINUX_REPO ?= "github.com/CHERI-Alliance/linux.git"
META_CHERI_LINUX_BRANCH ?= "codasip-cheri-riscv-6.18"
META_CHERI_LINUX_PROTOCOL ?= "https"

META_CHERI_LTP_REPO ?= "github.com/CHERI-Alliance/ltp.git"
META_CHERI_LTP_BRANCH ?= "master"
META_CHERI_LTP_PROTOCOL ?= "https"

META_CHERI_OPENSBI_REPO ?= "github.com/CHERI-Alliance/opensbi.git"
META_CHERI_OPENSBI_BRANCH ?= "codasip-cheri-riscv"
META_CHERI_OPENSBI_PROTOCOL ?= "https"

META_CHERI_QEMU_REPO = "github.com/CHERI-Alliance/qemu.git"
META_CHERI_QEMU_BRANCH = "alliance-codasip"
META_CHERI_QEMU_PROTOCOL = "https"

META_CHERI_U_BOOT_REPO ?= "github.com/CHERI-Alliance/u-boot.git"
META_CHERI_U_BOOT_BRANCH ?= "codasip-cheri-riscv"
META_CHERI_U_BOOT_PROTOCOL ?= "https"