# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-cheri-distro"
BBFILE_PATTERN_meta-cheri-distro = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-cheri-distro = "15"

BBFILES_DYNAMIC += " \
    openembedded-layer:${LAYERDIR}/dynamic-layers/openembedded-layer/*/*/*.bb \
    openembedded-layer:${LAYERDIR}/dynamic-layers/openembedded-layer/*/*/*.bbappend \
    gnome-layer:${LAYERDIR}/dynamic-layers/gnome-layer/*/*/*.bbappend \
    networking-layer:${LAYERDIR}/dynamic-layers/networking-layer/*/*/*.bbappend \
    multimedia-layer:${LAYERDIR}/dynamic-layers/multimedia-layer/*/*/*.bbappend \
"

LAYERDEPENDS_meta-cheri-distro = " meta-cheri-toolchain"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_meta-cheri-distro = "1"

LAYERSERIES_COMPAT_meta-cheri-distro = "scarthgap"

META_CHERI_BUSYBOX_REPO ?= "github.com/CHERI-Alliance/busybox.git"
META_CHERI_BUSYBOX_BRANCH ?= "codasip-cheri-riscv-1_36_1"
META_CHERI_BUSYBOX_PROTOCOL ?= "https"

META_CHERI_GDB_REPO = "github.com/CHERI-Alliance/gdb.git"
META_CHERI_GDB_BRANCH = "codasip-cheri-riscv"
META_CHERI_GDB_PROTOCOL = "https"

META_CHERI_OPENOCD_REPO ?= "github.com/CHERI-Alliance/openocd.git"
META_CHERI_OPENOCD_BRANCH ?= "codasip-cheri-riscv"
META_CHERI_OPENOCD_PROTOCOL ?= "https"

# Suport for CHERI
DISTROOVERRIDES:append = "${@bb.utils.contains('DISTRO_FEATURES', 'cheri', ':cheri', '', d)}"
DISTRO_FEATURES_FILTER_NATIVE:append = " cheri"
DISTRO_FEATURES_FILTER_NATIVESDK:append = " cheri"
