FILESEXTRAPATHS:prepend := "${THISDIR}/fontconfig:"
SRC_URI:append:class-target = " \
    file://cheribsd.patch;striplevel=0 \
    file://cheri-fixes.patch \
"

do_configure:prepend:class-target() {
    # Remove fc-lang/fclang.h not to include it instead of _build/fc-lang/fclang.h
    # that is generated by patched fc-lang/fc-lang.py.
    rm -f ${S}/fc-lang/fclang.h
}
