#!/bin/sh
# stolen from postgresql-cheri

PGENGINE=/usr/bin
LIBDIR=/usr/lib/

if [ -x /sbin/runuser ]
then
    SU=runuser
else
    SU=su
fi

POSTGRES_INSTANCE="/tmp/postgres-test-cheri/instance"

PG_REGRESS=${LIBDIR}/postgresql/pgxs/src/test/regress/pg_regress

SCHEDULE_NAME=${SCHEDULE_NAME:-serial_schedule}

OUTPUT_DIR="/tmp/pg_test"

rm -rf $OUTPUT_DIR

mkdir -p $OUTPUT_DIR
mkdir -p $OUTPUT_DIR/log
mkdir -p $OUTPUT_DIR/sql
mkdir -p $OUTPUT_DIR/expected
mkdir -p $OUTPUT_DIR/results
mkdir -p $OUTPUT_DIR/testtablespace
mkdir -p $POSTGRES_INSTANCE

cd $OUTPUT_DIR

if "${PG_REGRESS}" "--inputdir=${LIBDIR}/postgresql/pgxs/src/test/regress" "--bindir=${PGENGINE}" "--dlpath=${LIBDIR}"  "--schedule=${LIBDIR}/postgresql/pgxs/src/test/regress/${SCHEDULE_NAME}" "--outputdir=$OUTPUT_DIR" "--temp-instance=$POSTGRES_INSTANCE" "$@"
then
	echo "TESTS SUCCCEEDED"
else
	if [ "$?" = 1 ]; then
		echo "TESTS UNSTABLE"
		echo "CHECKING FOR ASSERTION FAILURES:"
		grep TRAP "$OUTPUT_DIR/log/postmaster.log" || true
		exit 0
	else
		echo "Got test failures, reading initdb log: $OUTPUT_DIR/log/initdb.log"
		cat "$OUTPUT_DIR/log/initdb.log"
		false
	fi
fi

cp /tmp/pg_test/regression.diffs regression.diffs
cp /tmp/pg_test/regression.out regression.out
cp -rf /tmp/pg_test/expected .
cp -rf /tmp/pg_test/results .
cp /tmp/pg_test/log/postmaster.log postmaster.log